image: ruby:2.4.2

stages:
  - test
  - publish

before_script:
  - bundle config jobs 8
  - bundle install --path=/tmp/bundler --quiet

rubocop:
  stage: test
  script:
    - bundle exec rubocop

rspec:
  stage: test
  script:
    - bundle exec rspec
